<a href="https://colab.research.google.com/github/itsmesudhanshu/pyton-learning/blob/main/DAP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Numpy**

In [ ]:

Sure, I can help you find the factors of a number in Python! To do that, you can use a loop to iterate through all the numbers from 1 to the given number, an

AttributeError: module 'math' has no attribute 'Factorial'

In [ ]:
import numpy as np
names=['sudhanshu','chouhan','great']
Emp_list=np.array(names)
print(Emp_list)

['sudhanshu' 'chouhan' 'great']


In [ ]:
#how to create a 2d array
import numpy as np
names=['sudhanshu','chouhan','great']
age=[1,2,3]
Emp_list1=np.array([names,age])
print(Emp_list1)

[['sudhanshu' 'chouhan' 'great']
 ['1' '2' '3']]


In [ ]:
import numpy as np
kite=np.zeros([3,3])
print(kite)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
yuvraj=np.arange(1,10,2)
print(yuvraj)

[1 3 5 7 9]


In [ ]:
import numpy as np
sal=np.linspace(1,10,5)
print(sal)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
import numpy as np
list1=[1.0,2.8,3.6,4.7]
tim=["tom","jerry"]
kin=np.array(list1)
mit=np.array(tim)
print(kin)
print(type(kin))
print(kin.dtype)
print(mit)
print(mit.dtype)
print([mit.shape])
print(mit.itemsize)

[1.  2.8 3.6 4.7]
<class 'numpy.ndarray'>
float64
['tom' 'jerry']
<U5
[(2,)]
20


In [ ]:
import numpy as np

l1=np.arange(12)
print(l1)
l2=l1.reshape(3,4)
print(l2)
l3=l1.reshape(2,2,3)
print(l3)
l5=np.array([1,2,3])
print(l5)
print(l5.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[1 2 3]
(3,)


#Pandas Data Series

In [ ]:
import pandas as pd
price=pd.Series(data=[30,60,20],index=['Ice cream','pizza','coke'])
print(price)

Ice cream    30
pizza        60
coke         20
dtype: int64


## Data Series With a sequence of numbers

In [ ]:
import pandas as pd
table=pd.Series(range(2,21,2))
print(table)

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
8    18
9    20
dtype: int64


##How to create a Data Series Using a Python Dictionary

In [ ]:
import pandas as pd
book=pd.Series({'B001':301,'B002':302,'B003':303})
print(book)

B001    301
B002    302
B003    303
dtype: int64


In [ ]:
import pandas as pd
da=pd.Series(data='1D',index=['pen','pencil','pins'])
print(da)

pen       1D
pencil    1D
pins      1D
dtype: object


##How to create a Series that include Missing values using NaN


In [ ]:
import pandas as pd
da2= pd.Series(data=[1,np.nan,5],index=['class','sudhanshu','chouhan'])
print(da2)


class        1.0
sudhanshu    NaN
chouhan      5.0
dtype: float64


In [ ]:
import pandas as pd
import numpy as np
var1=np.arange(1,6)
sqr=pd.Series(index=var1,data=var1*var1)
print(sqr)

1     1
2     4
3     9
4    16
5    25
dtype: int64


#Operators

##Airthematic Operators

In [ ]:
a=10
b=5
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)

15
5
50
2.0
2


In [ ]:
# %
20%3

2

In [ ]:
20**3

8000

In [ ]:
"Sudhanshu"+2

TypeError: can only concatenate str (not "int") to str

In [ ]:
"Sudhanshu"+"Chouhan" #String concatenate


'SudhanshuChouhan'

In [ ]:
ao="3"+"2"
print(ao)
print(type(ao))

32
<class 'str'>


In [ ]:
"Sudhanshu"*"Sudhanshu"

TypeError: can't multiply sequence by non-int of type 'str'

In [ ]:
"SUdhanshu"*2

'SUdhanshuSUdhanshu'

##Relational Operators
<,>,<=,>=,!=,==

In [ ]:
10<20

True

In [ ]:
10>20

False

In [ ]:
20>=20

True

In [ ]:
20<=20

True

In [ ]:
20!=20

False

In [ ]:
20==20

True

In [ ]:
#relational Operators is also applicable to string also
str1="Sudhanshu"
str2="Chouhan"
str1<str2

False

In [ ]:
a=100
id(a)

136376184491344

In [ ]:
#Relational operators does not work in complex no.
2 + 3i < 3+ i

SyntaxError: invalid decimal literal (<ipython-input-63-7513cb2088fc>, line 2)

In [ ]:
#Chaining is possible
10<20<30<40


True

In [ ]:
10>20<30<40

False

How to take input from user?

In [ ]:
a3=input()
a4=input()
a5=a3+a4
print(a5)
print(type(a3))
print(type(a4))
print(type(a5))
#It means in python input taken by user is aleays string


5
6
56
<class 'str'>
<class 'str'>
<class 'str'>


In [ ]:
a6=int(a3)
a7=int(a4)
a8=a6+a7
print(a8)

11


In [ ]:
print(type(a6))
print(type(a7))

<class 'int'>
<class 'int'>


In [ ]:
a9=int(input())
a10=int(input())
a11=a9+a10
print(a11)
print(type(a11))

5
6
11
<class 'int'>


##Logical Operator
and: if both operand is true the result is true

or : if any one is true the result is true

not:reverse

works on all type of data

In [ ]:
True and False

False

In [ ]:
True and True

True

In [ ]:
True or True

True

In [ ]:
True or False

True

In [ ]:
10 and 20

20

In [ ]:
0 and 20

0

In [ ]:
 1 and 20

20

In [ ]:
10 and 'sudhanshu'

'sudhanshu'

In [ ]:
2+3j and 'sudhanshu'

'sudhanshu'

"For string only empty string represent false"
"sudhanshu" and "Chouhan"

#"For string only empty string represent false"
"sudhanshu" and "Chouhan"


In [ ]:
"sudhanshu" and "Chouhan"

'Chouhan'

In [ ]:
"" and "Chouhan"

''

In [ ]:
"a" or "b"

'a'

In [ ]:
10 or 20

10

In [ ]:
0 or 20

20

In [ ]:
"sudhanshu" or "chouhan"

'sudhanshu'

In [ ]:
'' or "Chouhan"

'Chouhan'

In [ ]:
not(False)

True

In [ ]:
not(2)

False

In [ ]:
not("Sudhanshu"v)

False

In [ ]:
not(0)

True

In [ ]:
not("")

True

In [ ]:
#Conversion of decimal  into binary

##Bitwise Operator
int and bool pe work karte hain

In [ ]:
6 & 7

6

In [ ]:
6 | 7

7

In [ ]:
x=10
x=x+10
print(x)

20


In [ ]:
t=9
t+=9
t

18

The same has been followed by
x=x-10==x-=10

x=x*10== x*=10

x=x/10== x/=10

x=x//10 == x// = 10

These are known as short hand.

Membership operator

In [ ]:
"P" in "Pankaj"

True

In [ ]:
"p" in "Pankaj"

False

In [ ]:
j1="I am not in danger Skyler, I am the danger"
"danger" in j1



True

In [ ]:
"Skyler, I am the danger" in j1

True

In [ ]:
"Skyler, am" not in j1

True

In [ ]:
l1=[1,2,3,"Pankaj"]
print("Pankaj" in l1)

True


s1=(1,2,3,"Pankaj")
print(2 in s1)

In [ ]:
print("Hello")
print()
print("hello")
#print function by default convert empty space in place of print() function

Hello

hello


In [ ]:
q1=10
q2=20
q3=30
print(q1,q2,q3)
#Output values are separated by space
#If you want to specify any other seperator
print(q1,q2,q3, sep="@")
print(q1,q2,q3, sep="")

10 20 30
10@20@30
102030


In [ ]:
print("Sudhanshu"+ "Chouhan")

SudhanshuChouhan


In [ ]:
print("Sudhanshu","Chouhan")#By default space is separator

Sudhanshu Chouhan


In [ ]:
a=10
b=20
print("The sum of a is", a+b)

The sum of a is 30


# **Control Flow**

##Conditional

If and Else

In [ ]:
a= int(input("Enter the number"))
b=int(input("Enter the number"))
print("1")
print("2")
if a<b:
  print("3")

Enter the number5
Enter the number6
1
2
3


In [ ]:
# take a input from keyboard and print if it is even or odd
e1= int(input("Take number from keyboard"))
if e1%2==0:
  print(e1,"is even number")
else:
  print(e1,"is odd number")

Take number from keyboard5
5 is odd number


In [ ]:
e2=int(input("Please enter the year"))
if e2%400==0:
  print(e2, "is a leap year")
elif e2%100==0 :
  print(e2,"is not a leap year")
elif e2%4==0:
  print(e2,"is a leap year")
else:
  print(e2,"is not aleap year")

Please enter the year1562
1562 is not aleap year


In [ ]:
#Find maximum among 3 distinct number
n1=int(input("Enter the first number"))
n2=int(input("Enter the second number"))
n3=int(input("Enter the third number"))
if n1>n2 and n1>n3:
  print(n1, "is largest among the these number")
else:
  if n2>n3:
    print(n2, "is largest among the these number")
  else:
    print(n3, "is largest among the these number")

Enter the first number36
Enter the second number45
Enter the third number21
45 n2 is largest among the these number


#Iterative element

In [ ]:
for x in "Sudhanshu":
  print(x)

S
u
d
h
a
n
s
h
u


In [ ]:
i=0
for x in "Sudhanshu":
  print("The element at index",i ,"is",x)
  i=i+1

The element at index 0 is S
The element at index 1 is u
The element at index 2 is d
The element at index 3 is h
The element at index 4 is a
The element at index 5 is n
The element at index 6 is s
The element at index 7 is h
The element at index 8 is u


In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
for i in range(1,5):
  print(i)

1
2
3
4


In [ ]:
for i in range(5):
  print("Sudhanshu")

Sudhanshu
Sudhanshu
Sudhanshu
Sudhanshu
Sudhanshu


In [ ]:
#Program to add element from the list
l22=[24,23,45,65,76]
total=0
for i in range(0,len(l22)):
  total=total+l22[i]
print(total)


233


In [ ]:
for i in range(1,101):
  if(i%2==0):
    print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [ ]:
for i in range(5,1):
  print(i)

In [ ]:
for i in range(5,2,-1):
  print(i)

5
4
3


In [ ]:
m1=int(input())
for i in range(m1):
  print("*",end=" ")


5
* * * * * 

In [ ]:
m3=int(input())
for i in range(m3):
  print("*")

5
*
*
*
*
*


In [ ]:
m2=int(input())
for i in range(m2):
  for j in range(m2):
    print("*",end=" ")
  print()

5
* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [ ]:
m3=int(input())
for i in range(m3):
  for j in range(i+1):
    print("*",end=" ")
  print()

5
* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
m4=int(input())
for i in range(m4):
  for j in range(i,m4):
    print("*",end=" ")
  print()

5
* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
m5=int(input())
for i in range(m5):
  for j in range(i+1):
    print(j+1,end=" ")
  print()

5
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [ ]:
m6=int(input())
for i in range(m6):
  for j in range(m6-i-1):
    print(" ",end=" ")
  for j in range(i+1):
    print("*",end=" ")
  for j in range(i):
    print("*",end=" ")
  print()


5
        * 
      * * * 
    * * * * * 
  * * * * * * * 
* * * * * * * * * 


In [ ]:
#Factor of a number
m7= int(input())
for i in range(1,m7+1):
  if m7%i==0:
    print(i)



6
1
2
3
6


In [ ]:
#Storing Factors of a number in a list
m8=int(input())
l31=[]
for i in range(1,m8+1):
  if m8%i==0:
    l31.append(i)
print(l31)

24
[1, 2, 3, 4, 6, 8, 12, 24]


In [ ]:
#COde for perfect number
#Perfect number is a number in which the sum of the factor excluding the number itself is equal to the number"""
m9=int(input())
t=0
for i in range(1,m9):
  if m9%i==0:
    t=t+i
if t==m9:
  print("The number is perfect number")
else:
  print("The number is not a perfect number")

6
The number is perfect number


In [ ]:
#Sum of digit of number
m10=int(input())
t1=0
while m10!=0:
     t1=m10%10+t1
     m10=m10//10
print(t1)



1564
16


In [ ]:
#Armstrong number
m11=int(input())
m12=m11
t2=0
l15=len(str(m11))
while m11!=0:
  k=m11%10
  t2=(k)**l15+t2
  m11=m11//10
if t2==m12:
  print(m12,"is a armstrong number")
else:
  print(m12,"is not a armstrong number")

123
123 is not a armstrong number


In [ ]:
#Factorial of number
m13=int(input())
n1=1
for i in range(m13,0,-1):
  n1=i*n1
print("Factorial of",m13,"is",n1)

9
Factorial of 9 is 362880


In [ ]:
# Strong number : A number is a strong number is said to be a strong number if the sum of factorial of digit
#in  the number is equals to the number itself
m14=int(input())
m15=m14
n2=1
sum1=0
while m14!=0:
  j1=m14%10
  for i in range(j1,0,-1):
    n2=i*n2
  sum1=n2+sum1
  n2=1
  m14=m14//10
if sum1==m15:
  print("The number is a strong number")
else:
  print("Not a strong number")


40585
The number is a strong number


In [ ]:
  sum1=sum1+n2
  m14=m14//10
print(sum1)
if sum1==m15:
  print("The number",m15,"is a strong number")
else:
  print("The number", m15,"is not a strong number")

In [ ]:
#Find the product of first five natural numbers(1,2,3,4,5)
prod=1
for i in range(1,6):
  prod=prod*i
print(prod)

120


In [ ]:
# FOr finding n factorial
n11=int(input())
fact=1
for i in range(1,n11+1):
  fact=fact*i
print(fact)

7
5040


In [ ]:
l21=[1,2,3,4,5,6]
sum=0
for i in l21:
  sum=sum+i
print(sum)

21


In [ ]:
l22=eval(input("Enter a list"))
sum1=0
for i in l22:
  sum1=sum1+i
print(sum1)

Enter a list5,6,9,4,2
26


In [ ]:
# eval function
r1=eval(input("Enter any sequence "))
print(type(r1))

Enter any sequence [1,2,3,4]
<class 'list'>


Take the two number and print the largest

In [ ]:
t1= int(input("Enter First number"))
t2=int(input("Enter second number"))
c= t1 if t1>t2 else t2
print(c)

Enter First number5
Enter second number6
6


In [ ]:
#Prime number program



SyntaxError: invalid syntax (<ipython-input-2-8c2a2bef5eea>, line 4)

In [ ]:
#Sum of all factor of number

Take three distinct number and print the largest(Through nesting)

In [ ]:
t3= int(input("Enter First number"))
t4=int(input("Enter Second number"))
t5= int(input("Enter Third NUmber"))
t6= t3 if t3>t4 and t3>t5 else t4 if t4>t5 else t5
print(t6)

Enter First number6
Enter Second number4
Enter Third NUmber5
6


a=10
b=20
can be written as a,b=10,20



##**Continue**

Skip the remaining portion of current iteration and continue with the next iteration.

In [ ]:
for i in range(1,11):
  print("Sudhanshu")
  if i%3==0:
    continue
  print(i)

Sudhanshu
1
Sudhanshu
2
Sudhanshu
Sudhanshu
4
Sudhanshu
5
Sudhanshu
Sudhanshu
7
Sudhanshu
8
Sudhanshu
Sudhanshu
10


#**Data Structure**

##**Python List**

Introduction to list

Creating a list

Features of a list

Python List: A collection of similiar or different types of a data item.

In [ ]:
l1=[1,2,3,4,5,6,7]
print(l1)

[1, 2, 3, 4, 5, 6, 7]


In [ ]:
#Empty list
l0=[]
print(l0)


[]


In [ ]:
#A list with duplicate items
l2=[1,2,3,4,4,5,5,6,6]
print(l2)


[1, 2, 3, 4, 4, 5, 5, 6, 6]


In [ ]:
# A list with different types of item
l3=[1,2,"N",3.145]
print(l3)

[1, 2, 'N', 3.145]


## Features of list
###1.Duplicate items
###2.Mutable
###3.Various datatype storage


#Accessing element
1.Accessing element of Single dimensional list

2.Negative indexing

3.Accessing Element of a Multi dimensional list

In [ ]:
l5=[2,4,6,8,10]

l5[3]

8

In [ ]:
#Negative Indexing
#Accessing element from the last
l5[-1]

10

In [ ]:
#Accessing multi dimensional list: Multi dimensional list is a list contgaining another list
l6=[[1,2,3,4],"om",[4,5,6,8]]
l6[2][1]

5

##Adding element to a list

1.append () Method: A built in method to add an item at the end of a list
list.append(value)
2. insert()Method:
3. extent ()Method

In [ ]:
l7=[1,2,3,4]
l7

[1, 2, 3, 4]

###Append method: Add element at the end of the list.

In [ ]:
#Append

l7.append(5)
l7

[1, 2, 3, 4, 5]

In [ ]:
# Adding more than one element:For this duplicate the append method
l7.append(6)
l7.append(7)
l7.append(8)
l7


[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
#Adding a list as an item:
l7.append([2,3,4])
l7

[1, 2, 3, 4, 5, 6, 7, 8, [2, 3, 4]]

###Insert ()Method: A built in method to add an item at a specific position
###list.insert(position, value)


In [ ]:
l7.insert(3,5)
l7

[1, 2, 3, 5, 4, 5, 6, 7, 8, [2, 3, 4]]

###Extend method: It is a method in which we will add item of one list into another list.
list1.extend(list2)


In [ ]:
l7
l8=[11,12,13]
l7.extend(l8)
l7

[1, 2, 3, 5, 4, 5, 6, 7, 8, [2, 3, 4], 11, 12, 13]

###Input method
#####Used to take input from the user
##### User input is always coverted to a string.

In [ ]:
o1=input()

65


In [ ]:
##Typecasting
o2=int(input())
type(o2)

54


int

###Input a list using loop

In [ ]:
o3=int(input("Enter the number of element "))
l11=[]
for i in range(o3):
  n11=int(input())
  l11.append(n11)
l11


Enter the number of element 5
1
2
8
5
6


[1, 2, 8, 5, 6]

###Split method
#####Split a string into a list of substring
#### string.split(separator, maxsplit)

In [ ]:
str11="my name is khan"
str11.split()

['my', 'name', 'is', 'khan']

In [ ]:
num11=input("Enter the number").split()
num11

Enter the number45 65 98 24


['45', '65', '98', '24']

In [ ]:
n21=int(input("Enter the number of element: "))
num21= input("Enter the number: ").split()
for i in range(0,n21):
  num21[i]=int(num21[i])
num21

Enter the number of element: 5
Enter the number: 65 85 32 10 21


[65, 85, 32, 10, 21]

In [ ]:
#Changing an item
l51=["Sudhanshu","Chouhan",45,65,63,"hero"]
l51[3]="All time"
l51

['Sudhanshu', 'Chouhan', 45, 'All time', 63, 'hero']

In [ ]:
#Changing multiple range of values
l61=["srk","sk","ad","sak","ak",1,2,4]
l61[3:5]=["ak"]
l61

['srk', 'sk', 'ad', 'ak', 1, 2, 4]

##Removing the item
###Remove an item using the remove() Method
### Remove an item using the pop() Method
### Remove an item using the del keyword
### Clear the list using the clear() Method

In [ ]:
l61=["Sudhanshu","Chouhan","Samatrix"]
l61.remove("Sudhanshu")
l61

['Chouhan', 'Samatrix']

In [ ]:
l71=["Sudhanshu","Chouhan","Samatrix"]
l71.pop(1)
l71
#If the index is not specified then the last item will be deleted


['Sudhanshu', 'Samatrix']

l81=["Sudhanshu","Chouhan","Samatrix"]
del l81
l81


In [ ]:
l81=["Sudhanshu","Chouhan","Samatrix"]
del l81
l81

NameError: name 'l81' is not defined

In [ ]:
l91=["Sudhanshu","Chouhan","Samatrix"]
l91.clear()
l91

[]

In [ ]:
#Python program to convert the month name to a number of days


1.Calculate the sum of all numbers from 1 to a given number

2.Write a program to print multiplication table of a given number

3.Display numbers from a list using loop

4.Count the total number of digits in a number

5.Print the following pattern

6.Print list in reverse order using a loop

7.Display numbers from -10 to -1 using for loop

8.Use else block to display a message “Done” after successful execution of for
loop

9.Write a program to display all prime numbers within a range

10.Display Fibonacci series up to 10 terms

11.Find the factorial of a given number

12.Reverse a given integer number

13.Use a loop to display elements from a given list present at odd index positions

14.Calculate the cube of all numbers from 1 to a given number

15.Find the sum of the series upto n terms

In [ ]:
##Introduction to  List Comprehension
###Provide a shorter syntax while creating a new list from the existing.
###

In [ ]:
name1=["Amogh","Shreyansh","Shreyansh","Vikram","Vishal"]
S_names=[]
for i in name1:
  if "S" in i:
    S_names.append(name1)

S_names


[['Amogh', 'Shreyansh', 'Shreyansh', 'Vikram', 'Vishal'],
 ['Amogh', 'Shreyansh', 'Shreyansh', 'Vikram', 'Vishal']]

In [ ]:
name1=["Amogh","Shreyansh","Sharma","Vikram","Vishal"]
S_names=[]
for name in name1:
  if "S" in name:
    S_names.append(name)

S_names


['Shreyansh', 'Sharma']

In [ ]:
S_name=[name for name in name1 if "S" in name]
S_name

['Shreyansh', 'Sharma']

###Syntax:list=[expression for item in iterable if condition== True]
####Condition checking is optional here

In [ ]:
S_name= [name for name in name1 if "S" in name]
S_name

['Shreyansh', 'Sharma']

In [ ]:
name1_copy=[name for name in name1]
name1_copy

['Amogh', 'Shreyansh', 'Sharma', 'Vikram', 'Vishal']

#Dictionary

##A collection of key-value pairs.
##Syntax: dict_name={key1:value1, key2: value2,....}

In [1]:
name={"Kapil": "anshul","saurabh":"agarwal"}
name

{'Kapil': 'anshul', 'saurabh': 'agarwal'}

In [2]:
###Can not have two item with same key.
name1={"Kapil":"anshul","Kapil":"Narayan","Saurabh":"agarwal"}
name1

{'Kapil': 'Narayan', 'Saurabh': 'agarwal'}

In [5]:
#Dictionaries are mutable
name2={"Kapil":"anshul","saurabh":"agarwal"}
name2["Kapil"]="narayan"
name2

{'Kapil': 'narayan', 'saurabh': 'agarwal'}

##Length of a dictionary
###Can be determined using the len() function.
### Gives the count of key-value pairs of a dictionary

In [6]:
name3={"Kapil":"anshul","saurabh":"agarwal"}
len(name3)

2

##The dict() Constructor

Alternative way to create a dictionary

In [7]:
name4=dict(Kapil="anshul",saurabh="agarwal")
name4

{'Kapil': 'anshul', 'saurabh': 'agarwal'}

##Accessing elements from dictionary

###Accessing values using key Names
###Accessing values using get() Method
###Accessing keys using keys() Method
### Accessing values using values() Method
###Accessing Items using items() Methods

In [8]:
#Accessing values using key Names
name4={"Kapil":"anshul","saurabh":"agarwal"}
name4["Kapil"]

'anshul'

In [9]:
#Accessing values using get() Method
name5={"Kapil":"anshul","saurabh":"agarwal"}
name5.get("Kapil")

'anshul'

In [16]:
#Acessing key using keys() Method
#Return a view object reflects any changes done to the dictionary.
name6={"Kapil":"anshul","saurabh":"agarwal"}
name6_keys=name6.keys()
name6_keys


dict_keys(['Kapil', 'saurabh'])

In [17]:
name6["Atul"]="Patidar"
name6.keys()

dict_keys(['Kapil', 'saurabh', 'Atul'])

In [14]:
#Acessing values using values() Method
#Return a view object reflects any changes done to the dictionary.
name6={"Kapil":"anshul","saurabh":"agarwal"}
name6_values=name6.values()
name6_values


dict_values(['anshul', 'agarwal'])

In [15]:
name6["Atul"]="Patidar"
name6.values()

dict_values(['anshul', 'agarwal', 'Patidar'])

In [19]:
#Accessing items using
name6.items()

dict_items([('Kapil', 'anshul'), ('saurabh', 'agarwal'), ('Atul', 'Patidar')])

##Changing values using key names
##Changing values usnig update() Method
##Adding New Item using key Names
##Adding New item using update() Method

In [30]:
name7={'Kapil': 'anshul', 'saurabh': 'agarwal', 'Atul': 'Patidar'}
name7

{'Kapil': 'anshul', 'saurabh': 'agarwal', 'Atul': 'Patidar'}

In [31]:
name7["Kapil"]="narayan"
name7

{'Kapil': 'narayan', 'saurabh': 'agarwal', 'Atul': 'Patidar'}

In [34]:
#USing update
name8={'Kapil': 'anshul', 'saurabh': 'agarwal', 'Atul': 'Patidar'}
name8.update({"Kapil":"narayan"})
name8

{'Kapil': 'narayan', 'saurabh': 'agarwal', 'Atul': 'Patidar'}

In [35]:
#Adding items using key names
name9={'Kapil': 'anshul', 'saurabh': 'agarwal', 'Atul': 'Patidar'}
name9["Sudhanshu"]="Chouhan"
name9

{'Kapil': 'anshul',
 'saurabh': 'agarwal',
 'Atul': 'Patidar',
 'Sudhanshu': 'Chouhan'}

In [36]:
#Adding item using update
name10={'Kapil': 'anshul', 'saurabh': 'agarwal', 'Atul': 'Patidar'}
name10.update({"Sudhanshu":"Chouhan"})
name10

{'Kapil': 'anshul',
 'saurabh': 'agarwal',
 'Atul': 'Patidar',
 'Sudhanshu': 'Chouhan'}